<?php
namespace p7g\Discord\Gateway;

final class Event {
  public const READY = 'READY';

  public const CHANNEL_CREATE = 'CHANNEL_CREATE';
  public const CHANNEL_UPDATE = 'CHANNEL_UPDATE';
  public const CHANNEL_DELETE = 'CHANNEL_DELETE';
  public const CHANNEL_PINS_UPDATE = 'CHANNEL_PINS_UPDATE';

  public const GUILD_CREATE = 'GUILD_CREATE';
  public const GUILD_UPDATE = 'GUILD_UPDATE';
  public const GUILD_DELETE = 'GUILD_DELETE';
  public const GUILD_BAN_ADD = 'GUILD_BAN_ADD';
  public const GUILD_BAN_REMOVE = 'GUILD_BAN_REMOVE';
  public const GUILD_EMOJIS_UPDATE = 'GUILD_EMOJIS_UPDATE';
  public const GUILD_INTEGRATIONS_UPDATE = 'GUILD_INTEGRATIONS_UPDATE';
  public const GUILD_MEMBER_ADD = 'GUILD_MEMBER_ADD';
  public const GUILD_MEMBER_REMOVE = 'GUILD_MEMBER_REMOVE';
  public const GUILD_MEMBER_UPDATE = 'GUILD_MEMBER_UPDATE';
  public const GUILD_MEMBERS_CHUNK = 'GUILD_MEMBERS_CHUNK';
  public const GUILD_ROLE_CREATE = 'GUILD_ROLE_CREATE';
  public const GUILD_ROLE_UPDATE = 'GUILD_ROLE_UPDATE';
  public const GUILD_ROLE_DELETE = 'GUILD_ROLE_DELETE';

  public const MESSAGE_CREATE = 'MESSAGE_CREATE';
  public const MESSAGE_UPDATE = 'MESSAGE_UPDATE';
  public const MESSAGE_DELETE = 'MESSAGE_DELETE';
  public const MESSAGE_DELETE_BULK = 'MESSAGE_DELETE_BULK';
  public const MESSAGE_REACTION_ADD = 'MESSAGE_REACTION_ADD';
  public const MESSAGE_REACTION_REMOVE = 'MESSAGE_REACTION_REMOVE';
  public const MESSAGE_REACTION_REMOVE_ALL = 'MESSAGE_REACTION_REMOVE_ALL';

  public const PRESENCE_UPDATE = 'PRESENCE_UPDATE';

  public const TYPING_START = 'TYPING_START';

  public const USER_UPDATE = 'USER_UPDATE';

  public const VOICE_STATE_UPDATE = 'VOICE_STATE_UPDATE';
  public const VOICE_SERVER_UPDATE = 'VOICE_SERVER_UPDATE';

  public const WEBHOOKS_UPDATE = 'WEBHOOKS_UPDATE';
}
